version: "3.1"

language: en

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 3
  max_ngram: 5
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100

policies:
- name: RulePolicy
  core_fallback_threshold: 0.4
  core_fallback_action_name: "utter_not_understood"
  enable_fallback_prediction: true
- name: MemoizationPolicy
- name: TEDPolicy
  max_history: 5
  epochs: 25
assistant_id: 20251023-133614-broad-glaze
